spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shop?useSSL=false&serverTimezone=Europe/Warsaw
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  liquibase:
    contexts: prod